repos:
  - repo: local
    hooks:
      # Run the linter
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]
        args: [--fix]
      # Run the formatter
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
      # Run tests
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [tests/]
